apiVersion: v1
kind: Pod
metadata:
  name: csi-os-test-nginx
  namespace: default
spec:
  containers:
    - name: csi-os-test-nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html/os
          name: webroot
  volumes:
    - name: webroot
      persistentVolumeClaim:
        claimName: csi-os-pvc
        readOnly: false
