apiVersion: v1
kind: Pod
metadata:
  name: csi-cos-test-nginx
  namespace: default
spec:
  containers:
    - name: csi-cos-test-nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html/cos
          name: webroot
  volumes:
    - name: webroot
      persistentVolumeClaim:
        claimName: csi-cos-pvc
        readOnly: false
