apiVersion: v1
kind: Secret
metadata:
  name: csi-os-secret
  namespace: kube-system
stringData:
  accessKeyID: 
  secretAccessKey: 
  # endpoint 写访问地址，例如 <region>.xxx.xxx 不包含 bucket 名字
  endpoint:
  # 挂载命令，根据镜像分辨，可选 cosfs、ossfs，也用来区分不同服务端
  mounter: