---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-os
provisioner: csi.os
# reclaimPolicy: Retain
parameters:
  # -d,--debug  set log level to debug 
  options: ""
  bucket: <bucketname>
  csi.storage.k8s.io/provisioner-secret-name: csi-os-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: csi-os-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-os-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-os-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
