---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-cos
provisioner: csi.cosfs
parameters:
  mounter: cosfs
  options: ""
  # to use an existing bucket, specify it here:
  bucket: k8scsi-profiver-1256163609
  csi.storage.k8s.io/provisioner-secret-name: csi-cos-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: csi-cos-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-cos-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-cos-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
